mytasks/urls.py
from django.urls import path
from . import views

app_name = "mytasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

tasks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mytasks/', include("mytasks.urls"))
]

mytasks/models.py
from django.db import models

# Create your models here.

mytasks/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse


class NewTaskForm(forms.Form):
  task = forms.CharField(label="New Task")

# Create your views here.

def index(request):

  if "tasks" not in request.session:
    request.session["tasks"] = []
  
  return render(request, "mytasks/index.html", {
    "tasks" : request.session["tasks"]
  })

def add(request):

  if request.method == "POST":
    form = NewTaskForm(request.POST)
  
    if form.is_valid():
      task = form.cleaned_data["task"]
      request.session["tasks"] += [task]
      return HttpResponseRedirect(reverse("mytasks:index"))
    
    else:
      return render(request, "mytasks/add.html", {
        "form" : form
      })
  
  return render(request, "mytasks/add.html", {
    "form" : NewTaskForm()
  })

mytasks/templates/mytasks/add.html
{% extends "mytasks/layout.html" %}

{% block body %}
  <h1>Add Task</h1>
  <div class="form">
    <form action="{% url 'mytasks:add' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <br>
      <input class="submit" type="submit" name="Add Task">
    </form>
  <div class="transitionlink"><a href="{% url 'mytasks:index' %}">View Tasks</a></div>
  </div>
{% endblock %}

mytasks/templates/mytasks/index.html
{% extends "mytasks/layout.html" %}

{% block body %}
  <h1>Tasks</h1>
  <div class="tasks">
    <ul>
      {% for task in tasks %}
        <li>{{ task }}</li>
      {% empty %}
        <li>No Tasks</li>
      {% endfor %}
    </ul>
    <br>
  <div class="transitionlink"><a href="{% url 'mytasks:add' %}">Add New Task</a></div>
  </div>
{% endblock %}

mytasks/templates/mytasks/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'mytasks/style.css' %}">
    <title>MyTasks</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>